# Generated by Django 3.2 on 2021-08-15 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTag', models.CharField(max_length=200, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('link', models.URLField(max_length=400, verbose_name='Link')),
                ('descripcion', models.CharField(max_length=2000, verbose_name='Descripcion')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tag', to='aportes.Tag')),
            ],
        ),
    ]
